name: fly.io deployment

on:
  push:
    branches: ["master"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-website:
    if: github.repository_owner == 'terrablue'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --no-cache -c fly.toml
